# Generated by Django 2.0.1 on 2018-03-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('translate', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
            ],
        ),
    ]
