# Generated by Django 2.0.1 on 2018-03-17 04:08

from django.db import migrations, models
import django.db.models.deletion

def create_continent(apps, schema_editor):
    #Obtengo el modelo de continent de la app Continents
    Continent = apps.get_model("continents","Continent")

    Continent.objects.create(name="asia",translate="asia",color="red")
    Continent.objects.create(name='america',translate='america',color='green')
    Continent.objects.create(name='africa',translate='africa',color='blue')
    Continent.objects.create(name='europa',translate='europe',color='orange')
    Continent.objects.create(name='antartida',translate='antarctica',color='yellow')
    Continent.objects.create(name='australia',translate='australia',color='purple')
    
class Migration(migrations.Migration):

    dependencies = [
        ('continents', '0001_initial'),
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_continent),
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='continents.Continent'),
            preserve_default=False,
        ),
    ]
